### ISSUE TITLE
Security: Client Side Session Tampering

### ISSUE THREAD

**Issue by jlchereau** [Memba/Kidoju-Server#31]
# Client Side Session Tampering
## Overview:
The Authentication library in the client uses the location hash to transmit and retrieve the auth token. This data is not verified in any way before being accepted into the localStorage auth object.

A few implications of this vulnerability:
* The redirect_uri allows for %23(\#) to be injected, which could result in forcing a user to log into an attackers account without their knowledge, publish sensitive information while under the attackers account, resulting in information leakage.
* Simply by clicking a link with #access_id set, an attacker can either force a user to log out, or to log into another account.
* An attacker can set a token to never expire, which may either decrease the security of the token, or cause denial of service when an expired token is attempted to be used while the client app believes the token is not expired.

## Recommendations:
We recommend that you verify these values on the client before allowing them to be set. One way to do this would be to require that the state parameter be included, store it in localStorage on sign-in, and verify that the state parameter in the url fragment matches the local one before assigning values.

**Comment by jlchereau** [comment]
The flow has been modified as follows.

A suggested, the state is now generated in the browser that initiates the flow - https://github.com/Memba/Kidoju-Server/blob/master/client/js/app.rapi.js#L415

```js
getSignInUrl: function (provider, returnUrl) {
    rapi.util.log('calling getSignInUrl for ' + provider);
    var state = rapi.util.getFingerPrint() + '-' + rapi.util.getRandomNumber();
    rapi.util.setState(state);
    return $.ajax({
        url: rapi.util.format(rapi.root + rapi.oauth.endPoints.signIn, provider),
        type: GET,
        cache: true,
        data: { //data is automatically encoded (encodeURIComponent) by jQuery
            returnUrl: rapi.util.cleanUrl(returnUrl),
            state: state
        }
    });
    //TODO delete token???
},
```

**Comment by jlamendo** [comment]
This looks good Jacques! 

The only input I have here is to ensure you use a cryptographically secure entropy source for the additional value in state.

I have a UUID generator here which does this task, you might find it useful as is, or an example of how to get secure entropy in the browser.

```javascript
var uuid = function(){
  var Seed = function(){
    var b=[];
    Array.apply([],crypto.getRandomValues(new Uint8Array(32))).forEach(function(c){
      b=b.concat(c.toString(16).split(""));
    });
    return function(i){
      var t = "";
      switch(i){
        case 8: t +='-';
        case 12: t +='4';break;
        case 16: t +='-'+ (parseInt(b.pop(),16) & 3 | 8).toString(16); break;
        case 20: t +='-';
        default: t += b.pop();
    }
    return t;
    };
  };
  var uuid='';
  var seed = Seed();

  for (var i = 0; i < 32; i++) {
   uuid += seed(i);
  }
  return uuid;
};
```

minified:
```javascript
function(){for(var c="",f=function(){var d=[];Array.apply([],crypto.getRandomValues(new Uint8Array(32))).forEach(function(c){d=d.concat(c.toString(16).split(""))});return function(c,b){b="";switch(c){case 8:b+="-";case 12:b+="4";break;case 16:b+="-"+(parseInt(d.pop(),16)&3|8).toString(16);break;case 20:b+="-";default:b+=d.pop()}return b}}(),e=0;32>e;e++)c+=f(e);return c};
```
