### ISSUE TITLE
Security: Validate Http Headers and CORS

### ISSUE THREAD

**Issue by jlchereau** [Memba/Kidoju-Server#32]
See discussion at https://github.com/helmetjs/helmet/issues/43

See headers at https://github.com/Memba/Kidoju-Server/blob/master/api/middleware/headers.js

See CORS at https://github.com/Memba/Kidoju-Server/blob/master/api/routes/index.js#L48

**Comment by jlamendo** [comment]
CORS configuration should be just fine, as you are using a bearer token for authentication. That prevents any CSRF problems.

In regards to which headers are applicable, I suggest implementing all of them even in places where they may not be needed for simplicities sake. A JSON API doesn't need a CSP header, but the frontend for that JSON API does. But, adding a CSP header to responses from the JSON API will not have any negative effects outside of a very minor amount of bandwidth.

I didn't include this in the report for that reason - the security headers in use here are fine for an API.
