### ISSUE TITLE
Security: Prevent IP spoofing in the oAuth flow

### ISSUE THREAD

**Issue by jlchereau** [Memba/Kidoju-Server#35]
See https://github.com/Memba/Kidoju-Server/blob/master/api/routes/authenticationRoute.js#L358

**Comment by jlchereau** [comment]
Response from ^Lift

If your architecture prevents accessing the true IP address of the user, a good solution that provides a greater level of protection against IP spoofing is to use a client side library like fingerprint.js to generate a unique browser fingerprint, and validate against that. Fingerprinting is highly accurate, and the id's are very difficult to fake. A simple way to do this would be to add the browsers fingerprint in a header and validate this in addition to the IP. As long as the attacker is unable to run JavaScript on the valid user's browser, this ID is a reasonably safe way to distinguish one user from another.

**Comment by jlchereau** [comment]
First I had to change the validation of ip addresses to allow for IPv6 addresses because ```req.connection.remoteAddress``` returns:

- 127.0.0.1 in nodeJS 0.10.x and 0.11.x  up to 0.11.13
- ::ffff:127.0.0.1 in nodeJS 0.11.x where x >= 14
- ::1 in nodeJS 0.12.0

The change is located at https://github.com/Memba/Kidoju-Server/blob/master/api/db/schemaValidators.js#L88

Then instead of adding a header, a fingerprint is now added to the state which is now generated by the user browser as per [^Lift's recommendation](https://github.com/Memba/Kidoju-Server/issues/31)

The function that creates the fingerprint relies on https://github.com/Valve/fingerprintJS with a fallback if it is missing - See https://github.com/Memba/Kidoju-Server/blob/master/client/js/app.rapi.js#L103:

```js
getFingerPrint: function() {
    var hash = 0;
    if ($.type(window.Fingerprint) === 'function' && window.Fingerprint.constructor.name === 'Function') {
        hash = new window.Fingerprint({canvas: true, ie_activex: false, screen_resolution: true}).get();
    } else if (window && window.navigator && window.navigator.userAgent) {
        //See http://stackoverflow.com/questions/7616461/generate-a-hash-from-string-in-javascript-jquery
        var chr, agent = window.navigator.userAgent;
        hash = 0;
        for (var i = 0; i < agent.length; i++) {
            chr   = agent.charCodeAt(i);
            /* jshint -W016 */
            hash  = ((hash << 5) - hash) + chr;
            hash |= 0; // Convert to 32bit integer
            /* jshint +W016 */
        }
    }
    return hash;
},
```

*Note that there is a deprecation warning on https://github.com/Valve/fingerprintJS#deprecation-warning. We have not implemented https://github.com/Valve/fingerprintjs2 because (1) it is still work in progress, and (2) it relies on flash which is a nogo on some devices.*

**Comment by jlamendo** [comment]
This works well enough. I wouldn't rely on the IP or a fingerprint for a large portion of security, but it is well enough to add an additional layer of protection.
